
FROM ubuntu:16.04
MAINTAINER Chris Davie "cjdavie@googlemail.com"

# ubuntu-y things

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get dist-upgrade -y

RUN apt-get update --fix-missing
RUN apt-get install -y sudo
#RUN rm -rf /var/lib/apt/lists/*

RUN apt-get install -y openssl
RUN apt-get install -y wget --fix-missing
RUN wget -O /tmp/eclipse.tar.gz http://www.mirrorservice.org/sites/download.eclipse.org/eclipseMirror/technology/epp/downloads/release/neon/2/eclipse-cpp-neon-2-linux-gtk-x86_64.tar.gz
RUN tar -xf /tmp/eclipse.tar.gz -C /opt
RUN rm /tmp/eclipse.tar.gz

RUN apt-get install -y default-jre
RUN apt-get install -y x11-xserver-utils
RUN apt-get upgrade -y

# these make eclipse pretty
RUN apt-get install -y libxext-dev libxrender-dev libxtst-dev

ADD run /usr/local/bin/eclipse

RUN chmod +x /usr/local/bin/eclipse && \
    mkdir -p /home/chris && \
    echo "chris:x:1000:1000:chris,,,:/home/chris:/bin/bash" >> /etc/passwd && \
    echo "chris:x:1000:" >> /etc/group && \
    echo "chris ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/chris && \
    chmod 0440 /etc/sudoers.d/chris && \
    chown chris:chris -R /home/chris && \
    chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo

#RUN  echo "    IdentityFile ~/.ssh/id_rsa" >> /etc/ssh/ssh_config

RUN mkdir /home/chris/.ssh
RUN chmod a=rwx /home/chris/.ssh

USER chris

ENV HOME /home/chris
WORKDIR /home/chris
CMD /usr/local/bin/eclipse
