FROM chris/eclipse_neon
MAINTAINER Chris Davie "cjdavie@googlemail.com"

USER root

RUN apt-get install -y firefox
RUN locale-gen en_US.UTF-8
RUN apt-get install -y less


# other numerical packages

RUN apt-get install -y libblas-dev liblapack-dev
RUN apt-get install -y gfortran libatlas-dev g++ gcc
RUN apt-get install -y libfreetype6-dev  

# Python stuff
RUN apt-get install -y build-essential python3 python3-dev
RUN apt-get install -y build-essential python python-dev
RUN apt-get install -y software-properties-common python-software-properties
RUN add-apt-repository -y ppa:jonathonf/python-3.6
RUN apt-get update
RUN apt-get install -y python3.6


# pip2 packages

RUN apt-get install -y python-pip
RUN pip install --upgrade pip
RUN apt-get install -y python-pip
RUN pip install --upgrade pip
RUN pip install Cython
RUN pip install numpy --upgrade
RUN pip install scipy --upgrade
RUN pip install futures --upgrade
RUN pip install psutil --upgrade
RUN pip install sqlalchemy --upgrade
RUN pip install pylint --upgrade

# pip3 packages

RUN apt-get install -y python3-pip

RUN pip3 install -U pip
RUN pip3 install -U numpy 
RUN pip3 install -U scipy
RUN apt-get install -y libfreetype6 libfreetype6-dev
RUN ln -s /usr/include/freetype2/ft2build.h /usr/include/
RUN apt-get install -y libpng12-0 libpng12-dev
RUN pip3 install -U matplotlib
RUN pip3 install sqlalchemy --upgrade
RUN pip3 install pylint --upgrade

# iPython
RUN pip3 install -U ipython

# sqlalchemy

# git

RUN apt-get install -y git man unzip

USER chris

ENV BROWSER /usr/bin/firefox
ENV HOME /home/chris
ENV LC_ALL en_US.utf8
WORKDIR /home/chris

